### ISSUE TITLE
AppEngine Test Automation

### ISSUE THREAD

**Issue by conneryn** [c6o/provisioners#177]
### Business Requirements:
Manually testing AppEngine apps is very time-consuming.  We need an automated mechanism to validate and test the installation of an AppEngine application.

### Features:
The exact feature requirements are still in flux, but potential requirements:
- [ ] Schema validation to ensure the AppEngine app matches the spec.
- [ ] CLI dry run with validation to ensure that outputted schema is valid K8s resources (kubeval?)
- [ ] Automated CLI installation to a mock cluster (ex: all within a [GitHub Actions](https://github.com/helm/kind-action)?)
- [ ] Autorun publish to hub (--dry-run ?)
- [ ] Automated CLI installation to a real cluster.

### Technical Considerations:
Provide any additional technical and/or architectural details.

### UX/UI Design:
Optionally add wireframes, mockups, prototypes, etc.
